Jenkinsfile, trade_portal/config/settings/test.py
Adds support for CI testing with a trigger for deployment on successful testing of commits to the master branch 
removes some extra settings dependencies for haystack which don't appear to be required at the moment
=> CI/CD Support for trade portal

Jenkinsfile, trade_portal/compose/production/django/celery/flower/start, trade_portal/compose/production/django/entrypoint
Support providing KMS prefix as a variable
=> fix(cicd): fix docker password setup

trade_portal/config/settings/kms.py, trade_portal/config/settings/production.py
Add support for collected the allowed host IP list for containers deployed using AWS Fargate
=> feat: fargate allowed hosts

Jenkinsfile
Adds quiet period to Jenkinsfile jobs to help with quick commits to a repo
=> fix: add quiet period to job triggers

trade_portal/trade_portal/static/_js/common.js, trade_portal/trade_portal/static/sass/_header.scss, trade_portal/trade_portal/static/sass/blocks/_items-list.scss, trade_portal/trade_portal/static/sass/pages/_autorise.scss, trade_portal/trade_portal/static/sass/pages/_home.scss, trade_portal/trade_portal/templates/base.html
=> fixes(markup): Header mobile menu, homepage sizes, document advance filter fixes after QA

Jenkinsfile
run build on docker-compose startup
=> fix(cicd): rebuild docker containers on startup

Jenkinsfile
update hamlet config for artefacts
=> fix: pipeline run

tradetrust/open-attestation-api/Dockerfile, tradetrust/open-attestation-verify-api/Dockerfile
Nothing special here just fixed permission errors that occurred because probably something changed in the docker images globally.
=> FIX: permission errors for SLS local tests

Jenkinsfile, tradetrust/document-store-worker/src/worker/__init__.py, tradetrust/document-store-worker/tests/integration/test.py
Minor fix to the gas price configuration to allow for an explicit price to be defined.
added tests and added testing to jenkins
=> fix(tradetrust): allow for fixed gas price to be defined

Jenkinsfile, tradetrust/monitoring/.gitignore
Adds support for ethereum network and account monitoring as part of https://github.com/gs-gs/ha-igl-p2/issues/414
=> CI/CD Build support for ethereum monitoring

tradetrust/document-store-worker/src/worker/__init__.py, tradetrust/document-store-worker/tests/unit/test_gas_price_adjustment.py
We're getting ```replacement transaction underpriced``` errors which basically means that a replacement transaction is simply not expensive enough to replace an older transaction. Therefore, instead of trying to update gas price using ```web.eth.generateGasPrice``` method, we'll use simple multiplication by a factor of ```1.1```. This seems to be the recommended method of handling such situations.
=> FIX: replacement transaction underpriced error fix

tradetrust/document-store-worker/src/worker/__init__.py
Another small improvement for the document store worker.  This turns ```underpriced replacement transaction``` error into a handled exception case.
=> FIX: better handling for underpriced replacement transaction error

tradetrust/docker-compose.servers.yml, tradetrust/docker-compose.yml, tradetrust/document-store-contract/Dockerfile, tradetrust/open-attestation-verify-api/Dockerfile, tradetrust/open-attestation-verify-api/package-lock.json, tradetrust/open-attestation-verify-api/package.json, tradetrust/open-attestation-verify-api/src/app.js, tradetrust/open-attestation-verify-api/test/test.js
Changed the way oa-verify api handles the connection to the blockchain. Adam needs this in order to play with the whole trade portal locally.
=> FIX: oa-verify api now able to connect to local blockchain emulator

DEV.md, trade_portal/compose/local/django/celery/beat/start, trade_portal/demo-au.yml, trade_portal/demo-sg.yml, trade_portal/docker-compose.yml, trade_portal/trade_portal/documents/services/watermark.py, trade_portal/trade_portal/documents/views/documents.py
gs-gs/ha-igl-p2#485
@mrtnmrtn?
=> feat(pdf): Use different way to parse the first page of PDF document

DEV.md, trade_portal/trade_portal/document_api/views.py, trade_portal/trade_portal/documents/admin.py, trade_portal/trade_portal/documents/forms.py, trade_portal/trade_portal/documents/services/watermark.py, trade_portal/trade_portal/documents/tasks.py, trade_portal/trade_portal/documents/templates/documents/issue.html, trade_portal/trade_portal/documents/views/documents_create.py
https://github.com/gs-gs/ha-igl-project/issues/82
=> feat(PDF/QR): Support PDF pages of any size for watermarking

trade_portal/trade_portal/documents/templates/documents/create.html, trade_portal/trade_portal/documents/urls.py, trade_portal/trade_portal/legi/abr.py, trade_portal/trade_portal/legi/views.py
After merging it we may re-design it or tune the process if they want, but I think that it's enough for initial business review (after QA passed)
#138
=> feat(create): Search parties by name as well as ABN 

trade_portal/trade_portal/documents/views/documents.py
gs-gs/ha-igl-project#104
Will implement test as separate PR after that another PR where some tests are done is merged
=> feat(documents): Download OA file with the same filename as the PDF upload

trade_portal/trade_portal/oa_verify/templates/oa_verify/verification.html, trade_portal/trade_portal/oa_verify/templates/oa_verify/verify_form.html, trade_portal/trade_portal/oa_verify/views.py
https://github.com/gs-gs/ha-igl-project/issues/53
IE ignored; mobile browsers support that and the message is displayed though I have no idea how to do it (but they support the technology so)
=> feat(verifier): Accept files dropped to the browser window

trade_portal/trade_portal/documents/forms.py, trade_portal/trade_portal/documents/views/documents_create.py
https://github.com/gs-gs/ha-igl-project/issues/159
=> feat(documents): Avoid document number duplication

tradetrust/open-attestation-verify-api/.gitignore, tradetrust/open-attestation-verify-api/docker-compose.yml, tradetrust/open-attestation-verify-api/package-lock.json, tradetrust/open-attestation-verify-api/package.json
from gs-gs/ha-igl-project#201
* upgrade other requirements to fix security issues
* add minimal docker-compose file to run standalone verify API without localstack stuff
=> fix(versions): Upgrade oa-verify JS library to actual version to avoid verify bug

DEV.md, trade_portal/config/healthcheck.py, trade_portal/config/settings/base.py, trade_portal/trade_portal/documents/services/lodge.py, trade_portal/trade_portal/documents/tasks.py
+some related celery debug because it behaved strange, without logs and so on
https://github.com/gs-gs/ha-igl-project/issues/106
=> Trade portal canary task and celery improvements

trade_portal/trade_portal/oa_verify/services.py, trade_portal/trade_portal/oa_verify/templates/oa_verify/document_provided.html
https://github.com/gs-gs/ha-igl-project/issues/259
=> feat(verifier): Correctly display v3 verification results

trade_portal/trade_portal/oa_verify/templates/oa_verify/document_provided.html
=> feat(verifier): Show Logs tab only for staff members

Jenkinsfile
If a URL is defined for the accounts cmdb, separately load the accounts and product cmdbs. Otherwise assume everything required is in the product cmdb.
Also revert `force_deploy` to its original value and add the ability when debugging to skip the trade portal tests.
=> refactor: accounts cmdb support

Jenkinsfile
- Adds support for auth via env var along with instance based config 
- Adds set -e to ensure multiple commands fail as expected within a shell block
=> cd: auth updates and script failure handling
